/* StreakFit — built-in training plans (a library to choose from).
 * Each plan: { id, name, subtitle, days:[{ title, exercises:[{key,sets,reps,rest}] }] }
 * `key` references an exercise in EXERCISES (js/exercises.js).
 */
const BUILTIN_PLANS = [
  {
    id: "aggressive_home_cut",
    name: "Aggressive Home Cut",
    subtitle: "6-day PPL · dumbbell + pull-up bar + bodyweight",
    days: [
      { title: "Day 1 — Push (Chest / Shoulders / Triceps)", exercises: [
        { key: "pushup", sets: 4, reps: "12–20", rest: 60 },
        { key: "floor_press", sets: 4, reps: "10–12", rest: 75 },
        { key: "ohp", sets: 3, reps: "10–12", rest: 75 },
        { key: "lateral_raise", sets: 3, reps: "15", rest: 45 },
        { key: "diamond_pushup", sets: 3, reps: "AMRAP", rest: 60 },
        { key: "burpee", sets: 3, reps: "10", rest: 45 },
      ] },
      { title: "Day 2 — Pull (Back / Biceps)", exercises: [
        { key: "pull_up", sets: 4, reps: "AMRAP", rest: 90 },
        { key: "bent_row", sets: 4, reps: "10–12", rest: 75 },
        { key: "single_row", sets: 3, reps: "12 / side", rest: 60 },
        { key: "db_curl", sets: 3, reps: "12", rest: 45 },
        { key: "hammer_curl", sets: 3, reps: "12", rest: 45 },
        { key: "dead_hang", sets: 3, reps: "30–45 s", rest: 45 },
      ] },
      { title: "Day 3 — Legs (Quads / Glutes / Hamstrings)", exercises: [
        { key: "goblet_squat", sets: 4, reps: "12–15", rest: 75 },
        { key: "reverse_lunge", sets: 3, reps: "12 / leg", rest: 60 },
        { key: "rdl", sets: 4, reps: "12", rest: 75 },
        { key: "glute_bridge", sets: 3, reps: "15", rest: 45 },
        { key: "calf_raise", sets: 4, reps: "20", rest: 30 },
        { key: "wall_sit", sets: 3, reps: "45 s", rest: 45 },
      ] },
      { title: "Day 4 — Push 2 (Strength focus)", exercises: [
        { key: "floor_press", sets: 5, reps: "8–10", rest: 90 },
        { key: "ohp", sets: 4, reps: "8–10", rest: 90 },
        { key: "pushup", sets: 3, reps: "AMRAP", rest: 60 },
        { key: "lateral_raise", sets: 4, reps: "15", rest: 45 },
        { key: "diamond_pushup", sets: 3, reps: "12", rest: 60 },
      ] },
      { title: "Day 5 — Pull 2 (Strength focus)", exercises: [
        { key: "pull_up", sets: 5, reps: "AMRAP", rest: 120 },
        { key: "bent_row", sets: 5, reps: "8–10", rest: 90 },
        { key: "single_row", sets: 3, reps: "10 / side", rest: 60 },
        { key: "hammer_curl", sets: 4, reps: "10", rest: 45 },
        { key: "dead_hang", sets: 3, reps: "Max", rest: 60 },
      ] },
      { title: "Day 6 — Conditioning / Core (HIIT)", exercises: [
        { key: "burpee", sets: 4, reps: "12", rest: 40 },
        { key: "high_knees", sets: 4, reps: "40 s", rest: 30 },
        { key: "mountain_climber", sets: 4, reps: "40 s", rest: 30 },
        { key: "jumping_jack", sets: 4, reps: "45 s", rest: 30 },
        { key: "plank", sets: 3, reps: "45–60 s", rest: 30 },
        { key: "bicycle_crunch", sets: 3, reps: "20 / side", rest: 30 },
      ] },
    ],
  },
  {
    id: "bodyweight_only",
    name: "Bodyweight Only",
    subtitle: "3-day · zero equipment, anywhere",
    days: [
      { title: "Day 1 — Upper / Push", exercises: [
        { key: "pushup", sets: 4, reps: "12–20", rest: 60 },
        { key: "diamond_pushup", sets: 3, reps: "AMRAP", rest: 60 },
        { key: "plank", sets: 3, reps: "45–60 s", rest: 45 },
        { key: "burpee", sets: 3, reps: "12", rest: 45 },
      ] },
      { title: "Day 2 — Lower", exercises: [
        { key: "bw_squat", sets: 4, reps: "20", rest: 60 },
        { key: "reverse_lunge", sets: 3, reps: "12 / leg", rest: 60 },
        { key: "glute_bridge", sets: 3, reps: "20", rest: 45 },
        { key: "calf_raise", sets: 4, reps: "25", rest: 30 },
        { key: "wall_sit", sets: 3, reps: "60 s", rest: 45 },
      ] },
      { title: "Day 3 — Full Body / HIIT", exercises: [
        { key: "burpee", sets: 4, reps: "12", rest: 40 },
        { key: "high_knees", sets: 4, reps: "40 s", rest: 30 },
        { key: "mountain_climber", sets: 4, reps: "40 s", rest: 30 },
        { key: "jumping_jack", sets: 4, reps: "45 s", rest: 30 },
        { key: "bicycle_crunch", sets: 3, reps: "20 / side", rest: 30 },
        { key: "plank", sets: 3, reps: "60 s", rest: 30 },
      ] },
    ],
  },
  {
    id: "dumbbell_4day",
    name: "Dumbbell Only",
    subtitle: "4-day · just a pair of dumbbells",
    days: [
      { title: "Day 1 — Push", exercises: [
        { key: "floor_press", sets: 4, reps: "10–12", rest: 75 },
        { key: "ohp", sets: 4, reps: "10–12", rest: 75 },
        { key: "lateral_raise", sets: 3, reps: "15", rest: 45 },
        { key: "pushup", sets: 3, reps: "AMRAP", rest: 60 },
      ] },
      { title: "Day 2 — Pull", exercises: [
        { key: "bent_row", sets: 4, reps: "10–12", rest: 75 },
        { key: "single_row", sets: 3, reps: "12 / side", rest: 60 },
        { key: "db_curl", sets: 3, reps: "12", rest: 45 },
        { key: "hammer_curl", sets: 3, reps: "12", rest: 45 },
      ] },
      { title: "Day 3 — Legs", exercises: [
        { key: "goblet_squat", sets: 4, reps: "12–15", rest: 75 },
        { key: "reverse_lunge", sets: 3, reps: "12 / leg", rest: 60 },
        { key: "rdl", sets: 4, reps: "12", rest: 75 },
        { key: "calf_raise", sets: 4, reps: "20", rest: 30 },
      ] },
      { title: "Day 4 — Full Body", exercises: [
        { key: "goblet_squat", sets: 3, reps: "15", rest: 60 },
        { key: "floor_press", sets: 3, reps: "12", rest: 60 },
        { key: "bent_row", sets: 3, reps: "12", rest: 60 },
        { key: "burpee", sets: 3, reps: "12", rest: 45 },
      ] },
    ],
  },
  {
    id: "fullbody_3day",
    name: "Full-Body 3-Day",
    subtitle: "3-day · efficient, hits everything",
    days: [
      { title: "Day A", exercises: [
        { key: "goblet_squat", sets: 4, reps: "12", rest: 75 },
        { key: "floor_press", sets: 4, reps: "10", rest: 75 },
        { key: "bent_row", sets: 4, reps: "10", rest: 75 },
        { key: "plank", sets: 3, reps: "45 s", rest: 45 },
      ] },
      { title: "Day B", exercises: [
        { key: "rdl", sets: 4, reps: "12", rest: 75 },
        { key: "ohp", sets: 4, reps: "10", rest: 75 },
        { key: "pull_up", sets: 4, reps: "AMRAP", rest: 90 },
        { key: "bicycle_crunch", sets: 3, reps: "20 / side", rest: 45 },
      ] },
      { title: "Day C", exercises: [
        { key: "reverse_lunge", sets: 4, reps: "12 / leg", rest: 60 },
        { key: "pushup", sets: 4, reps: "AMRAP", rest: 60 },
        { key: "single_row", sets: 4, reps: "12 / side", rest: 60 },
        { key: "burpee", sets: 3, reps: "12", rest: 45 },
      ] },
    ],
  },

  // ---- Named programs (raw exercise names + kcal; no key → generic demo) ----
  {
    id: "p90x", name: "P90X", subtitle: "Advanced · 13 weeks",
    days: [
      { title: "Chest & Back", exercises: [
        { name: "Standard Push-Up", sets: 3, reps: 15, kcal: 12 },
        { name: "Wide Front Pull-Up", sets: 3, reps: 10, kcal: 18 },
        { name: "Military Push-Up", sets: 3, reps: 12, kcal: 10 },
        { name: "Reverse Grip Chin-Up", sets: 3, reps: 10, kcal: 16 },
        { name: "Wide Fly Push-Up", sets: 3, reps: 12, kcal: 10 },
        { name: "Closed Grip Overhand Pull-Up", sets: 3, reps: 8, kcal: 14 },
        { name: "Decline Push-Up", sets: 3, reps: 10, kcal: 11 },
        { name: "Heavy Pants (Dumbbell Row)", sets: 3, reps: 12, kcal: 15 } ] },
      { title: "Plyometrics", exercises: [
        { name: "Jump Squat", sets: 4, reps: 20, kcal: 35 },
        { name: "Run-Stance Squat", sets: 3, reps: 20, kcal: 28 },
        { name: "Airborne Heisman", sets: 3, reps: 15, kcal: 30 },
        { name: "Swing Kick", sets: 3, reps: 20, kcal: 22 },
        { name: "Box Jump", sets: 3, reps: 15, kcal: 32 },
        { name: "Rock Star Hop", sets: 3, reps: 20, kcal: 30 },
        { name: "Gap Jump", sets: 3, reps: 15, kcal: 28 },
        { name: "Lateral Leapfrog Squat", sets: 3, reps: 12, kcal: 25 } ] },
      { title: "Shoulders & Arms", exercises: [
        { name: "Alternating Shoulder Press", sets: 3, reps: 12, kcal: 18 },
        { name: "In-Out Bicep Curl", sets: 3, reps: 12, kcal: 14 },
        { name: "Two-Arm Tricep Kickback", sets: 3, reps: 15, kcal: 12 },
        { name: "Deep Swimmer's Press", sets: 3, reps: 12, kcal: 16 },
        { name: "Full Supination Concentration Curl", sets: 3, reps: 10, kcal: 13 },
        { name: "Chair Dip", sets: 3, reps: 15, kcal: 14 },
        { name: "Upright Row", sets: 3, reps: 12, kcal: 16 },
        { name: "Static Arm Curl", sets: 3, reps: 12, kcal: 13 } ] },
      { title: "Yoga X", exercises: [
        { name: "Sun Salutation A", sets: 3, reps: 5, kcal: 20 },
        { name: "Warrior 1 to Warrior 2 Flow", sets: 2, reps: 8, kcal: 15 },
        { name: "Triangle Pose", sets: 2, reps: 6, kcal: 10 },
        { name: "Half Moon Pose", sets: 2, reps: 5, kcal: 12 },
        { name: "Twisting Triangle", sets: 2, reps: 5, kcal: 10 },
        { name: "Crow Pose", sets: 3, reps: 4, kcal: 8 },
        { name: "Yoga Belly 7", sets: 1, reps: 7, kcal: 14 },
        { name: "Dreya Roll", sets: 3, reps: 10, kcal: 12 } ] },
      { title: "Legs & Back", exercises: [
        { name: "Balanced Lunge", sets: 3, reps: 12, kcal: 22 },
        { name: "Calf Raise Squat", sets: 3, reps: 15, kcal: 18 },
        { name: "Reverse Grip Chin-Up", sets: 3, reps: 10, kcal: 16 },
        { name: "Super Skater", sets: 3, reps: 15, kcal: 25 },
        { name: "Wall Squat", sets: 3, reps: 20, kcal: 20 },
        { name: "Wide Front Pull-Up", sets: 3, reps: 10, kcal: 18 },
        { name: "Step Back Lunge", sets: 3, reps: 12, kcal: 20 },
        { name: "Alternating Side Lunge", sets: 3, reps: 12, kcal: 22 } ] },
      { title: "Kenpo X", exercises: [
        { name: "Jab Cross", sets: 3, reps: 30, kcal: 28 },
        { name: "Jab Cross Hook", sets: 3, reps: 25, kcal: 30 },
        { name: "Front Kick Back Kick", sets: 3, reps: 20, kcal: 35 },
        { name: "Side Kick", sets: 3, reps: 20, kcal: 30 },
        { name: "Back Kick Roundhouse", sets: 3, reps: 15, kcal: 32 },
        { name: "Three-Direction Kick", sets: 3, reps: 12, kcal: 30 },
        { name: "Sword Hammer", sets: 3, reps: 20, kcal: 22 },
        { name: "High Block Low Block", sets: 3, reps: 20, kcal: 20 } ] },
      { title: "Ab Ripper X", exercises: [
        { name: "In & Outs", sets: 1, reps: 25, kcal: 10 },
        { name: "Bicycle", sets: 1, reps: 25, kcal: 12 },
        { name: "Crunchy Frog", sets: 1, reps: 25, kcal: 10 },
        { name: "Wide Leg Sit-Up", sets: 1, reps: 25, kcal: 12 },
        { name: "Fifer Scissors", sets: 1, reps: 25, kcal: 11 },
        { name: "Hip Rock & Raise", sets: 1, reps: 25, kcal: 10 },
        { name: "Pulse Up", sets: 1, reps: 25, kcal: 9 },
        { name: "V-Up Roll-Up", sets: 1, reps: 25, kcal: 13 } ] },
    ],
  },
  {
    id: "centr", name: "Centr", subtitle: "All levels · 8 weeks",
    days: [
      { title: "HIIT Cardio", exercises: [
        { name: "Burpee", sets: 4, reps: 15, kcal: 40 },
        { name: "Mountain Climber", sets: 4, reps: 20, kcal: 30 },
        { name: "Jump Lunge", sets: 3, reps: 16, kcal: 35 },
        { name: "Lateral Shuffle", sets: 3, reps: 20, kcal: 28 },
        { name: "High Knees", sets: 4, reps: 30, kcal: 32 },
        { name: "Tuck Jump", sets: 3, reps: 12, kcal: 38 } ] },
      { title: "Strength — Upper Body", exercises: [
        { name: "Dumbbell Bench Press", sets: 4, reps: 10, kcal: 22 },
        { name: "Single-Arm Dumbbell Row", sets: 4, reps: 10, kcal: 20 },
        { name: "Dumbbell Shoulder Press", sets: 3, reps: 12, kcal: 18 },
        { name: "Bicep Curl", sets: 3, reps: 12, kcal: 14 },
        { name: "Tricep Overhead Extension", sets: 3, reps: 12, kcal: 13 },
        { name: "Lateral Raise", sets: 3, reps: 15, kcal: 12 },
        { name: "Face Pull", sets: 3, reps: 15, kcal: 11 } ] },
      { title: "Strength — Lower Body", exercises: [
        { name: "Goblet Squat", sets: 4, reps: 12, kcal: 28 },
        { name: "Romanian Deadlift", sets: 4, reps: 10, kcal: 30 },
        { name: "Walking Lunge", sets: 3, reps: 20, kcal: 26 },
        { name: "Sumo Squat", sets: 3, reps: 15, kcal: 24 },
        { name: "Glute Bridge", sets: 3, reps: 20, kcal: 16 },
        { name: "Standing Calf Raise", sets: 3, reps: 20, kcal: 10 } ] },
      { title: "Boxing", exercises: [
        { name: "Jab Cross Combo", sets: 4, reps: 20, kcal: 32 },
        { name: "Hook Uppercut Combo", sets: 4, reps: 16, kcal: 30 },
        { name: "Slip & Counter", sets: 3, reps: 15, kcal: 25 },
        { name: "Defensive Bob & Weave", sets: 3, reps: 20, kcal: 22 },
        { name: "Speed Bag Drill", sets: 3, reps: 30, kcal: 28 },
        { name: "Shadowboxing Round", sets: 3, reps: 1, kcal: 45 } ] },
      { title: "Mindfulness & Mobility", exercises: [
        { name: "Child's Pose Hold", sets: 2, reps: 3, kcal: 4 },
        { name: "Cat-Cow Flow", sets: 2, reps: 10, kcal: 5 },
        { name: "Hip Flexor Stretch", sets: 2, reps: 5, kcal: 5 },
        { name: "Seated Spinal Twist", sets: 2, reps: 5, kcal: 4 },
        { name: "Pigeon Pose", sets: 2, reps: 4, kcal: 5 },
        { name: "Foam Roll Thoracic Spine", sets: 2, reps: 10, kcal: 4 } ] },
    ],
  },
  {
    id: "cg_epic", name: "Caroline Girvan EPIC", subtitle: "Intermediate–Advanced · 10 weeks",
    days: [
      { title: "EPIC Legs", exercises: [
        { name: "Barbell Back Squat", sets: 5, reps: 8, kcal: 40 },
        { name: "Romanian Deadlift", sets: 4, reps: 10, kcal: 35 },
        { name: "Bulgarian Split Squat", sets: 4, reps: 10, kcal: 38 },
        { name: "Leg Press", sets: 4, reps: 12, kcal: 30 },
        { name: "Leg Curl", sets: 3, reps: 12, kcal: 18 },
        { name: "Hip Thrust", sets: 4, reps: 12, kcal: 22 },
        { name: "Standing Calf Raise", sets: 4, reps: 20, kcal: 12 } ] },
      { title: "EPIC Push", exercises: [
        { name: "Barbell Bench Press", sets: 5, reps: 6, kcal: 28 },
        { name: "Incline Dumbbell Press", sets: 4, reps: 10, kcal: 24 },
        { name: "Cable Chest Fly", sets: 3, reps: 12, kcal: 16 },
        { name: "Seated Dumbbell Shoulder Press", sets: 4, reps: 10, kcal: 20 },
        { name: "Arnold Press", sets: 3, reps: 12, kcal: 18 },
        { name: "Skull Crusher", sets: 3, reps: 12, kcal: 14 },
        { name: "Cable Tricep Pushdown", sets: 3, reps: 15, kcal: 12 } ] },
      { title: "EPIC Pull", exercises: [
        { name: "Deadlift", sets: 5, reps: 5, kcal: 45 },
        { name: "Pull-Up", sets: 4, reps: 8, kcal: 22 },
        { name: "Barbell Bent-Over Row", sets: 4, reps: 8, kcal: 30 },
        { name: "Seated Cable Row", sets: 3, reps: 12, kcal: 18 },
        { name: "Face Pull", sets: 3, reps: 15, kcal: 12 },
        { name: "Hammer Curl", sets: 3, reps: 12, kcal: 14 },
        { name: "Barbell Curl", sets: 3, reps: 10, kcal: 13 } ] },
      { title: "EPIC Core & Abs", exercises: [
        { name: "Dead Bug", sets: 3, reps: 12, kcal: 10 },
        { name: "Hollow Hold", sets: 3, reps: 8, kcal: 9 },
        { name: "Cable Crunch", sets: 3, reps: 15, kcal: 12 },
        { name: "Hanging Leg Raise", sets: 3, reps: 12, kcal: 14 },
        { name: "Pallof Press", sets: 3, reps: 12, kcal: 10 },
        { name: "Ab Wheel Rollout", sets: 3, reps: 10, kcal: 13 },
        { name: "Plank Hold", sets: 3, reps: 1, kcal: 8 } ] },
      { title: "EPIC Full Body HIIT", exercises: [
        { name: "Dumbbell Thrusters", sets: 4, reps: 15, kcal: 42 },
        { name: "Renegade Row", sets: 4, reps: 10, kcal: 35 },
        { name: "Kettlebell Swing", sets: 4, reps: 20, kcal: 38 },
        { name: "Box Step-Up with Knee Drive", sets: 3, reps: 12, kcal: 28 },
        { name: "Push-Up to Renegade Row", sets: 3, reps: 10, kcal: 30 },
        { name: "Dumbbell Snatch", sets: 3, reps: 10, kcal: 32 } ] },
    ],
  },
  {
    id: "fiton", name: "FitOn", subtitle: "All levels · 6 weeks",
    days: [
      { title: "Total Body Burn", exercises: [
        { name: "Bodyweight Squat", sets: 3, reps: 20, kcal: 22 },
        { name: "Push-Up", sets: 3, reps: 15, kcal: 14 },
        { name: "Reverse Lunge", sets: 3, reps: 16, kcal: 20 },
        { name: "Dumbbell Row", sets: 3, reps: 12, kcal: 18 },
        { name: "Glute Bridge", sets: 3, reps: 20, kcal: 14 },
        { name: "Plank Shoulder Tap", sets: 3, reps: 20, kcal: 12 },
        { name: "Jumping Jack", sets: 3, reps: 30, kcal: 20 } ] },
      { title: "Dance Cardio", exercises: [
        { name: "Salsa Step", sets: 4, reps: 32, kcal: 28 },
        { name: "Hip Sway Combo", sets: 4, reps: 24, kcal: 22 },
        { name: "Grapevine", sets: 3, reps: 20, kcal: 20 },
        { name: "Cha-Cha Step", sets: 3, reps: 24, kcal: 24 },
        { name: "Body Roll", sets: 3, reps: 16, kcal: 16 },
        { name: "Jump & Clap Combo", sets: 3, reps: 20, kcal: 28 } ] },
      { title: "Barre", exercises: [
        { name: "Parallel Pliés", sets: 3, reps: 20, kcal: 14 },
        { name: "Relevé Hold", sets: 3, reps: 15, kcal: 10 },
        { name: "Side Leg Lift", sets: 3, reps: 20, kcal: 12 },
        { name: "Arabesque Pulse", sets: 3, reps: 20, kcal: 12 },
        { name: "Curtsy Lunge", sets: 3, reps: 16, kcal: 16 },
        { name: "Inner Thigh Squeeze", sets: 3, reps: 20, kcal: 10 },
        { name: "Seated Ab Curl", sets: 3, reps: 15, kcal: 9 } ] },
      { title: "Pilates Core", exercises: [
        { name: "Hundred", sets: 1, reps: 100, kcal: 14 },
        { name: "Roll-Up", sets: 3, reps: 10, kcal: 10 },
        { name: "Single Leg Stretch", sets: 3, reps: 12, kcal: 10 },
        { name: "Double Leg Stretch", sets: 3, reps: 10, kcal: 12 },
        { name: "Criss-Cross", sets: 3, reps: 16, kcal: 11 },
        { name: "Teaser", sets: 3, reps: 8, kcal: 12 },
        { name: "Swan Dive", sets: 3, reps: 8, kcal: 9 } ] },
      { title: "Yoga Flow", exercises: [
        { name: "Sun Salutation B", sets: 3, reps: 5, kcal: 20 },
        { name: "Warrior Flow", sets: 2, reps: 6, kcal: 14 },
        { name: "Chair Pose Hold", sets: 3, reps: 5, kcal: 10 },
        { name: "Boat Pose", sets: 3, reps: 5, kcal: 9 },
        { name: "Lizard Pose", sets: 2, reps: 4, kcal: 8 },
        { name: "Supine Twist", sets: 2, reps: 4, kcal: 6 } ] },
      { title: "Strength Sculpt", exercises: [
        { name: "Dumbbell Squat Press", sets: 4, reps: 12, kcal: 30 },
        { name: "Bent-Over Row", sets: 3, reps: 12, kcal: 20 },
        { name: "Lateral Lunge with Curl", sets: 3, reps: 12, kcal: 22 },
        { name: "Chest Fly", sets: 3, reps: 15, kcal: 16 },
        { name: "Overhead Tricep Extension", sets: 3, reps: 15, kcal: 13 },
        { name: "Deadlift", sets: 4, reps: 10, kcal: 28 } ] },
    ],
  },
  {
    id: "bbg", name: "Sweat — BBG", subtitle: "Beginner–Intermediate · 12 weeks",
    days: [
      { title: "Legs BBG", exercises: [
        { name: "Jump Squat", sets: 4, reps: 15, kcal: 32 },
        { name: "Lunge", sets: 4, reps: 20, kcal: 28 },
        { name: "Sumo Squat", sets: 3, reps: 20, kcal: 24 },
        { name: "Step-Up", sets: 3, reps: 15, kcal: 22 },
        { name: "Donkey Kick", sets: 3, reps: 20, kcal: 14 },
        { name: "Fire Hydrant", sets: 3, reps: 20, kcal: 12 } ] },
      { title: "Arms & Abs BBG", exercises: [
        { name: "Push-Up", sets: 4, reps: 15, kcal: 14 },
        { name: "Tricep Dip", sets: 3, reps: 15, kcal: 13 },
        { name: "Commandos", sets: 3, reps: 12, kcal: 18 },
        { name: "Straight Leg Sit-Up", sets: 3, reps: 20, kcal: 12 },
        { name: "Leg Raise", sets: 3, reps: 15, kcal: 11 },
        { name: "Russian Twist", sets: 3, reps: 20, kcal: 12 },
        { name: "Bicycle Crunch", sets: 3, reps: 20, kcal: 11 } ] },
      { title: "Full Body BBG", exercises: [
        { name: "Burpee", sets: 4, reps: 10, kcal: 40 },
        { name: "Jump Lunge", sets: 4, reps: 16, kcal: 35 },
        { name: "Push-Up to Renegade Row", sets: 3, reps: 10, kcal: 28 },
        { name: "Squat to Press", sets: 3, reps: 15, kcal: 30 },
        { name: "Mountain Climber", sets: 3, reps: 20, kcal: 22 },
        { name: "Plank Up-Down", sets: 3, reps: 12, kcal: 16 } ] },
      { title: "LISS Cardio", exercises: [
        { name: "Power Walk", sets: 1, reps: 1, kcal: 200 },
        { name: "Elliptical", sets: 1, reps: 1, kcal: 220 },
        { name: "Cycling", sets: 1, reps: 1, kcal: 210 } ] },
      { title: "Yoga Recovery", exercises: [
        { name: "Downward Dog", sets: 3, reps: 5, kcal: 8 },
        { name: "Low Lunge Stretch", sets: 2, reps: 4, kcal: 6 },
        { name: "Seated Forward Fold", sets: 2, reps: 4, kcal: 5 },
        { name: "Figure Four Stretch", sets: 2, reps: 4, kcal: 5 },
        { name: "Supine Hamstring Stretch", sets: 2, reps: 4, kcal: 4 },
        { name: "Savasana", sets: 1, reps: 1, kcal: 3 } ] },
    ],
  },
  {
    id: "nml_build30", name: "Nourish Move Love — Build 30", subtitle: "Beginner–Intermediate · 8 weeks",
    days: [
      { title: "Lower Body", exercises: [
        { name: "Dumbbell Squat", sets: 4, reps: 12, kcal: 28 },
        { name: "Dumbbell Romanian Deadlift", sets: 4, reps: 10, kcal: 30 },
        { name: "Reverse Lunge", sets: 3, reps: 12, kcal: 22 },
        { name: "Sumo Squat Pulse", sets: 3, reps: 20, kcal: 20 },
        { name: "Single-Leg Glute Bridge", sets: 3, reps: 15, kcal: 16 },
        { name: "Lateral Band Walk", sets: 3, reps: 20, kcal: 12 } ] },
      { title: "Upper Body", exercises: [
        { name: "Dumbbell Push Press", sets: 4, reps: 10, kcal: 22 },
        { name: "Dumbbell Chest Press", sets: 4, reps: 10, kcal: 20 },
        { name: "Dumbbell Bent-Over Row", sets: 4, reps: 10, kcal: 20 },
        { name: "Lateral Raise", sets: 3, reps: 15, kcal: 12 },
        { name: "Bicep Curl to Shoulder Press", sets: 3, reps: 12, kcal: 16 },
        { name: "Tricep Kickback", sets: 3, reps: 15, kcal: 12 } ] },
      { title: "Full Body", exercises: [
        { name: "Dumbbell Deadlift", sets: 4, reps: 10, kcal: 32 },
        { name: "Push-Up", sets: 3, reps: 12, kcal: 14 },
        { name: "Dumbbell Front Squat", sets: 3, reps: 12, kcal: 28 },
        { name: "Dumbbell Upright Row", sets: 3, reps: 12, kcal: 16 },
        { name: "Reverse Lunge to Bicep Curl", sets: 3, reps: 12, kcal: 24 },
        { name: "Renegade Row", sets: 3, reps: 10, kcal: 22 } ] },
      { title: "Glutes & Core", exercises: [
        { name: "Hip Thrust", sets: 4, reps: 15, kcal: 22 },
        { name: "Cable Pull-Through", sets: 3, reps: 15, kcal: 18 },
        { name: "Clamshell", sets: 3, reps: 20, kcal: 10 },
        { name: "Dead Bug", sets: 3, reps: 10, kcal: 9 },
        { name: "Bird Dog", sets: 3, reps: 12, kcal: 9 },
        { name: "Pallof Press", sets: 3, reps: 12, kcal: 10 } ] },
      { title: "Cardio & Core", exercises: [
        { name: "Squat Jump", sets: 4, reps: 15, kcal: 34 },
        { name: "Mountain Climber", sets: 3, reps: 20, kcal: 24 },
        { name: "Dumbbell Swing", sets: 3, reps: 15, kcal: 28 },
        { name: "Plank to Downward Dog", sets: 3, reps: 10, kcal: 12 },
        { name: "Russian Twist", sets: 3, reps: 20, kcal: 12 },
        { name: "Hollow Body Hold", sets: 3, reps: 1, kcal: 8 } ] },
    ],
  },
  {
    id: "ntc", name: "Nike Training Club", subtitle: "All levels · 6 weeks",
    days: [
      { title: "Get Lean", exercises: [
        { name: "Sprint in Place", sets: 4, reps: 20, kcal: 30 },
        { name: "Squat to Lateral Kick", sets: 3, reps: 15, kcal: 24 },
        { name: "Push-Up Shuffle", sets: 3, reps: 12, kcal: 18 },
        { name: "Lunge with Twist", sets: 3, reps: 14, kcal: 22 },
        { name: "Burpee to Tuck Jump", sets: 3, reps: 10, kcal: 40 },
        { name: "Speed Skater", sets: 3, reps: 20, kcal: 28 } ] },
      { title: "Get Strong", exercises: [
        { name: "Barbell Squat", sets: 5, reps: 5, kcal: 38 },
        { name: "Deadlift", sets: 4, reps: 6, kcal: 40 },
        { name: "Bench Press", sets: 4, reps: 8, kcal: 26 },
        { name: "Weighted Pull-Up", sets: 4, reps: 6, kcal: 22 },
        { name: "Barbell Hip Thrust", sets: 4, reps: 10, kcal: 24 },
        { name: "Overhead Press", sets: 3, reps: 8, kcal: 20 } ] },
      { title: "Get Toned", exercises: [
        { name: "Resistance Band Squat", sets: 3, reps: 20, kcal: 22 },
        { name: "Dumbbell Lateral Raise", sets: 3, reps: 15, kcal: 12 },
        { name: "Tricep Dip", sets: 3, reps: 15, kcal: 13 },
        { name: "Glute Kickback", sets: 3, reps: 20, kcal: 14 },
        { name: "Curl & Press", sets: 3, reps: 12, kcal: 16 },
        { name: "Lateral Band Walk", sets: 3, reps: 20, kcal: 12 },
        { name: "Inner Thigh Raise", sets: 3, reps: 20, kcal: 10 } ] },
      { title: "Endurance Run Prep", exercises: [
        { name: "Dynamic Warm-Up", sets: 1, reps: 1, kcal: 20 },
        { name: "A-Skip", sets: 3, reps: 20, kcal: 15 },
        { name: "Butt Kick Drill", sets: 3, reps: 20, kcal: 14 },
        { name: "Lateral Band Run", sets: 3, reps: 15, kcal: 16 },
        { name: "Single-Leg Calf Raise", sets: 3, reps: 20, kcal: 10 },
        { name: "Hip Flexor March", sets: 3, reps: 20, kcal: 12 } ] },
      { title: "Yoga Recovery", exercises: [
        { name: "Child's Pose", sets: 2, reps: 3, kcal: 4 },
        { name: "Thread the Needle", sets: 2, reps: 4, kcal: 5 },
        { name: "Low Lunge Twist", sets: 2, reps: 4, kcal: 6 },
        { name: "Reclined Pigeon", sets: 2, reps: 4, kcal: 5 },
        { name: "Happy Baby", sets: 2, reps: 3, kcal: 4 },
        { name: "Legs Up the Wall", sets: 1, reps: 1, kcal: 3 } ] },
      { title: "Bodyweight Blast", exercises: [
        { name: "Push-Up", sets: 4, reps: 15, kcal: 14 },
        { name: "Jump Squat", sets: 4, reps: 15, kcal: 32 },
        { name: "V-Up", sets: 3, reps: 15, kcal: 13 },
        { name: "Reverse Lunge", sets: 3, reps: 16, kcal: 20 },
        { name: "Plank to Push-Up", sets: 3, reps: 10, kcal: 14 },
        { name: "Glute Bridge March", sets: 3, reps: 20, kcal: 14 } ] },
    ],
  },
];
